### ISSUE TITLE
windows下pip安装报UnicodeDecodeError

### ISSUE THREAD

**Issue by AioRos85** [bojone/bytepiece#20]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\LocalX\AppData\Local\Temp\pip-install-m82zpk8s\bytepiece_78856bb730d44450b525319f31404e89\setup.py", line 11, in <module>
          long_description=open('README_en.md').read(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 4: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by AioRos85** [comment]
open('README_en.md').read()
改为
open('README_en.md',encoding='utf-8').read()
